# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'acromine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for acromine
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 5.14'

  target 'acromineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'acromineUITests' do
    # Pods for testing
  end

end
